# -*- coding: utf-8 -*-
"""kmeans.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I0TwZfLH8JHBsZOdLJqROF4Vl1gJq6d_
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_blobs   # ONLY for data creation

# ------------------------------------------------
# 1️⃣ Generate synthetic dataset (3 clusters)
# ------------------------------------------------
X, _ = make_blobs(
    n_samples=300,
    centers=3,
    cluster_std=[1.0, 2.5, 0.8],
    random_state=42
)

# ------------------------------------------------
# 2️⃣ K-Means Algorithm from Scratch (NumPy only)
# ------------------------------------------------
def kmeans_from_scratch(X, K=3, max_iters=100):

    # Randomly choose K points as initial centroids
    random_indexes = np.random.choice(len(X), K, replace=False)
    centroids = X[random_indexes]

    for _ in range(max_iters):

        # Assignment step
        labels = []
        for point in X:
            distances = np.linalg.norm(point - centroids, axis=1)
            labels.append(np.argmin(distances))
        labels = np.array(labels)

        # Update step
        new_centroids = []
        for i in range(K):
            cluster_points = X[labels == i]
            new_centroids.append(cluster_points.mean(axis=0))
        new_centroids = np.array(new_centroids)

        # Convergence check
        if np.allclose(centroids, new_centroids):
            break

        centroids = new_centroids

    return labels, centroids


# ------------------------------------------------
# 3️⃣ Inertia (Sum of Squared Errors)
# ------------------------------------------------
def calculate_inertia(X, labels, centroids):
    inertia = 0
    for i in range(len(centroids)):
        cluster_points = X[labels == i]
        inertia += np.sum((cluster_points - centroids[i]) ** 2)
    return inertia


# ------------------------------------------------
# 4️⃣ Single Run (for visualization)
# ------------------------------------------------
labels, centroids = kmeans_from_scratch(X, K=3)
best_inertia = calculate_inertia(X, labels, centroids)

print("Best Run Inertia:", best_inertia)

# Visualization
plt.figure(figsize=(7, 6))
plt.scatter(X[:, 0], X[:, 1], c=labels, cmap='viridis', s=30)
plt.scatter(
    centroids[:, 0],
    centroids[:, 1],
    color='red',
    marker='X',
    s=200,
    label='Centroids'
)
plt.title("K-Means Clustering From Scratch")
plt.legend()
plt.show()

# ------------------------------------------------
# 5️⃣ Sensitivity Analysis (10 Random Runs)
# ------------------------------------------------
inertia_values = []

for i in range(10):
    labels, centroids = kmeans_from_scratch(X, K=3)
    inertia = calculate_inertia(X, labels, centroids)
    inertia_values.append(inertia)

mean_inertia = np.mean(inertia_values)
std_inertia = np.std(inertia_values)

print("\nInertia values from 10 runs:")
print(inertia_values)
print("Mean Inertia:", mean_inertia)
print("Standard Deviation:", std_inertia)